export const all_routes = {
  // Doctor Routes
  doctorDashboard: "/doctor-dashboard",
  doctorSignsSymps: "/signs-symptoms",
  doctorphysicalExams: "/physical-exams",
  doctorMypatients: "/my-patients",
  doctorProcedures: "/procedures",
  doctorPhysicain: "/physician",
  doctorHistory:"/history",
  doctorreviewofSystem: "/review-of-system",
  doctordrugsMeds: "/drugs-meds",
  doctorPatientLabDiag: "/patient-lab-diag",
  doctorDesposition: "/desposition",
  doctorSignatory: "/signatory",
  doctorDiagnosis: "/diagnosis",
  doctorWardCourse: "/ward-course",
  doctorDischargeInstruction: "/discharge-instruction",
  doctorPrintableForms: "/printable-forms",
  doctorPatientLog: "/patient-log",
doctorArchiveViewer: "/archive-viewer",
doctorReports: "/reports",

  // Nurse Routes
  nurseDashboard: "/nurse-dashboard",
  nurseRegDetails: "/Reg-Details",
  nurseForms: "/nurse-Forms",
  nurseAccomodation : "/Accomodation",
  nurseCharges: "/nurse-Charges",
  nursePreBill: "/Pre-Bill",
  nurseDischarge: "/nurse-Discharge",
  nursePatientLog: "/nurse-patient-log",
  nurseUtility: "/nurse-utility",
  nurseRequestTemplate: "/nurse-utility/request-template",
  nurseRequisition: "/nurse-utility/requisition",
  nurseReport: "/nurse-report",

  // Other Pages routes
  login: "/login",
  maintenance: "/maintenance",
  comingSoon: "/coming-soon",
  error404: "/error-404",
  error500: "/error-500",
  unauthorized: "/unauthorized",
};
